// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// iidMeanRcpp
Rcpp::List iidMeanRcpp(arma::vec Y, const arma::mat& X, const arma::vec& M, const arma::mat& P, const double ga, const double gb, arma::vec beta, double prec, const int N, const int p, const int nSims, const int nThin, const int nBurnin, const int nReport);
RcppExport SEXP _spTReg_iidMeanRcpp(SEXP YSEXP, SEXP XSEXP, SEXP MSEXP, SEXP PSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP betaSEXP, SEXP precSEXP, SEXP NSEXP, SEXP pSEXP, SEXP nSimsSEXP, SEXP nThinSEXP, SEXP nBurninSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< const double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< const int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(iidMeanRcpp(Y, X, M, P, ga, gb, beta, prec, N, p, nSims, nThin, nBurnin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// iidQuantileRcpp
Rcpp::List iidQuantileRcpp(const double tau, arma::vec Y, const arma::mat& X, const arma::vec& M, const arma::mat& P, const double ga, const double gb, arma::vec beta, double prec, const int N, const int p, const int nSims, const int nThin, const int nBurnin, const int nReport, const bool parallel, const int nThreads);
RcppExport SEXP _spTReg_iidQuantileRcpp(SEXP tauSEXP, SEXP YSEXP, SEXP XSEXP, SEXP MSEXP, SEXP PSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP betaSEXP, SEXP precSEXP, SEXP NSEXP, SEXP pSEXP, SEXP nSimsSEXP, SEXP nThinSEXP, SEXP nBurninSEXP, SEXP nReportSEXP, SEXP parallelSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< const double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< const int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type nReport(nReportSEXP);
    Rcpp::traits::input_parameter< const bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< const int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(iidQuantileRcpp(tau, Y, X, M, P, ga, gb, beta, prec, N, p, nSims, nThin, nBurnin, nReport, parallel, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// spMeanRcpp
Rcpp::List spMeanRcpp(arma::vec Y, const arma::mat& X, const arma::mat& U, const arma::mat& V, const std::vector<arma::mat>& X_alpha, const arma::mat& dist, const arma::vec& M, const arma::mat& P, const std::vector<arma::vec>& M_beta_alpha, const std::vector<arma::mat>& P_beta_alpha, const double da, const double db, const double ga, const double gb, const double na, const double nb, arma::vec beta, arma::mat gamma, arma::mat alpha, double prec, arma::mat hp, std::vector<arma::vec>& beta_alpha, const int N, const int n, const int p, const int q, const int r, const arma::vec& p_alpha, const arma::uvec& s, const int nSims, const int nThin, const int nBurnin, const int nReport);
RcppExport SEXP _spTReg_spMeanRcpp(SEXP YSEXP, SEXP XSEXP, SEXP USEXP, SEXP VSEXP, SEXP X_alphaSEXP, SEXP distSEXP, SEXP MSEXP, SEXP PSEXP, SEXP M_beta_alphaSEXP, SEXP P_beta_alphaSEXP, SEXP daSEXP, SEXP dbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP precSEXP, SEXP hpSEXP, SEXP beta_alphaSEXP, SEXP NSEXP, SEXP nSEXP, SEXP pSEXP, SEXP qSEXP, SEXP rSEXP, SEXP p_alphaSEXP, SEXP sSEXP, SEXP nSimsSEXP, SEXP nThinSEXP, SEXP nBurninSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::mat>& >::type X_alpha(X_alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::vec>& >::type M_beta_alpha(M_beta_alphaSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::mat>& >::type P_beta_alpha(P_beta_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type da(daSEXP);
    Rcpp::traits::input_parameter< const double >::type db(dbSEXP);
    Rcpp::traits::input_parameter< const double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< const double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< const double >::type na(naSEXP);
    Rcpp::traits::input_parameter< const double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hp(hpSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::vec>& >::type beta_alpha(beta_alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const int >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p_alpha(p_alphaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< const int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(spMeanRcpp(Y, X, U, V, X_alpha, dist, M, P, M_beta_alpha, P_beta_alpha, da, db, ga, gb, na, nb, beta, gamma, alpha, prec, hp, beta_alpha, N, n, p, q, r, p_alpha, s, nSims, nThin, nBurnin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// spQuantileRcpp
Rcpp::List spQuantileRcpp(const double tau, arma::vec Y, const arma::mat& X, const arma::mat& V, const std::vector<arma::mat>& X_alpha, const arma::mat& dist, const arma::vec& M, const arma::mat& P, const std::vector<arma::vec>& M_beta_alpha, const std::vector<arma::mat>& P_beta_alpha, const double da, const double db, const double ga, const double gb, const double na, const double nb, arma::vec beta, arma::mat alpha, double prec, arma::mat hp, std::vector<arma::vec>& beta_alpha, const int N, const int n, const int p, const int r, const arma::vec& p_alpha, const arma::uvec& s, const int nSims, const int nThin, const int nBurnin, const int nReport, const bool parallel, const int nThreads);
RcppExport SEXP _spTReg_spQuantileRcpp(SEXP tauSEXP, SEXP YSEXP, SEXP XSEXP, SEXP VSEXP, SEXP X_alphaSEXP, SEXP distSEXP, SEXP MSEXP, SEXP PSEXP, SEXP M_beta_alphaSEXP, SEXP P_beta_alphaSEXP, SEXP daSEXP, SEXP dbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP precSEXP, SEXP hpSEXP, SEXP beta_alphaSEXP, SEXP NSEXP, SEXP nSEXP, SEXP pSEXP, SEXP rSEXP, SEXP p_alphaSEXP, SEXP sSEXP, SEXP nSimsSEXP, SEXP nThinSEXP, SEXP nBurninSEXP, SEXP nReportSEXP, SEXP parallelSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::mat>& >::type X_alpha(X_alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::vec>& >::type M_beta_alpha(M_beta_alphaSEXP);
    Rcpp::traits::input_parameter< const std::vector<arma::mat>& >::type P_beta_alpha(P_beta_alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type da(daSEXP);
    Rcpp::traits::input_parameter< const double >::type db(dbSEXP);
    Rcpp::traits::input_parameter< const double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< const double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< const double >::type na(naSEXP);
    Rcpp::traits::input_parameter< const double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hp(hpSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::vec>& >::type beta_alpha(beta_alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p_alpha(p_alphaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< const int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type nReport(nReportSEXP);
    Rcpp::traits::input_parameter< const bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< const int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(spQuantileRcpp(tau, Y, X, V, X_alpha, dist, M, P, M_beta_alpha, P_beta_alpha, da, db, ga, gb, na, nb, beta, alpha, prec, hp, beta_alpha, N, n, p, r, p_alpha, s, nSims, nThin, nBurnin, nReport, parallel, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// spTMeanRcpp
double spTMeanRcpp();
RcppExport SEXP _spTReg_spTMeanRcpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(spTMeanRcpp());
    return rcpp_result_gen;
END_RCPP
}
// spTQuantileRcpp
double spTQuantileRcpp();
RcppExport SEXP _spTReg_spTQuantileRcpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(spTQuantileRcpp());
    return rcpp_result_gen;
END_RCPP
}
// krigeBayesRcpp
arma::mat krigeBayesRcpp(const arma::mat& w, const arma::mat& hp, const arma::mat& coords, const arma::mat& newcoords, const bool parallel, int nThreads);
RcppExport SEXP _spTReg_krigeBayesRcpp(SEXP wSEXP, SEXP hpSEXP, SEXP coordsSEXP, SEXP newcoordsSEXP, SEXP parallelSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type hp(hpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type newcoords(newcoordsSEXP);
    Rcpp::traits::input_parameter< const bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(krigeBayesRcpp(w, hp, coords, newcoords, parallel, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// dist1
arma::mat dist1(const arma::mat& coords);
RcppExport SEXP _spTReg_dist1(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(dist1(coords));
    return rcpp_result_gen;
END_RCPP
}
// dist2
arma::mat dist2(const arma::mat& coords);
RcppExport SEXP _spTReg_dist2(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(dist2(coords));
    return rcpp_result_gen;
END_RCPP
}
// dist_mat
arma::mat dist_mat(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _spTReg_dist_mat(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_mat(A, B));
    return rcpp_result_gen;
END_RCPP
}
// dtnorm
double dtnorm(double x, double mu, double sigma, double a, double b);
RcppExport SEXP _spTReg_dtnorm(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dtnorm(x, mu, sigma, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm
double rtnorm(double mu, double sigma, double a, double b);
RcppExport SEXP _spTReg_rtnorm(SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm(mu, sigma, a, b));
    return rcpp_result_gen;
END_RCPP
}
// psi1
double psi1(double x, double alpha, double lambda);
RcppExport SEXP _spTReg_psi1(SEXP xSEXP, SEXP alphaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(psi1(x, alpha, lambda));
    return rcpp_result_gen;
END_RCPP
}
// psi2
double psi2(double x, double alpha, double lambda);
RcppExport SEXP _spTReg_psi2(SEXP xSEXP, SEXP alphaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(psi2(x, alpha, lambda));
    return rcpp_result_gen;
END_RCPP
}
// rgig
arma::vec rgig(const int N, const double a, const arma::vec b, const double nu);
RcppExport SEXP _spTReg_rgig(SEXP NSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(rgig(N, a, b, nu));
    return rcpp_result_gen;
END_RCPP
}
// rig
arma::vec rig(const int N, const arma::vec& mu, const double lambda, const bool parallel, int nThreads);
RcppExport SEXP _spTReg_rig(SEXP NSEXP, SEXP muSEXP, SEXP lambdaSEXP, SEXP parallelSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rig(N, mu, lambda, parallel, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// ralRcpp
arma::vec ralRcpp(const arma::vec sigma, const double tau);
RcppExport SEXP _spTReg_ralRcpp(SEXP sigmaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(ralRcpp(sigma, tau));
    return rcpp_result_gen;
END_RCPP
}
// RandomMultiNormalC
arma::vec RandomMultiNormalC(const arma::mat& Q, const arma::vec& b);
RcppExport SEXP _spTReg_RandomMultiNormalC(SEXP QSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(RandomMultiNormalC(Q, b));
    return rcpp_result_gen;
END_RCPP
}
// ffbs
arma::mat ffbs(const arma::mat& Y, const double rho, const arma::mat& Sigma_w, const Rcpp::List& D_list);
RcppExport SEXP _spTReg_ffbs(SEXP YSEXP, SEXP rhoSEXP, SEXP Sigma_wSEXP, SEXP D_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_w(Sigma_wSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type D_list(D_listSEXP);
    rcpp_result_gen = Rcpp::wrap(ffbs(Y, rho, Sigma_w, D_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spTReg_iidMeanRcpp", (DL_FUNC) &_spTReg_iidMeanRcpp, 14},
    {"_spTReg_iidQuantileRcpp", (DL_FUNC) &_spTReg_iidQuantileRcpp, 17},
    {"_spTReg_spMeanRcpp", (DL_FUNC) &_spTReg_spMeanRcpp, 33},
    {"_spTReg_spQuantileRcpp", (DL_FUNC) &_spTReg_spQuantileRcpp, 33},
    {"_spTReg_spTMeanRcpp", (DL_FUNC) &_spTReg_spTMeanRcpp, 0},
    {"_spTReg_spTQuantileRcpp", (DL_FUNC) &_spTReg_spTQuantileRcpp, 0},
    {"_spTReg_krigeBayesRcpp", (DL_FUNC) &_spTReg_krigeBayesRcpp, 6},
    {"_spTReg_dist1", (DL_FUNC) &_spTReg_dist1, 1},
    {"_spTReg_dist2", (DL_FUNC) &_spTReg_dist2, 1},
    {"_spTReg_dist_mat", (DL_FUNC) &_spTReg_dist_mat, 2},
    {"_spTReg_dtnorm", (DL_FUNC) &_spTReg_dtnorm, 5},
    {"_spTReg_rtnorm", (DL_FUNC) &_spTReg_rtnorm, 4},
    {"_spTReg_psi1", (DL_FUNC) &_spTReg_psi1, 3},
    {"_spTReg_psi2", (DL_FUNC) &_spTReg_psi2, 3},
    {"_spTReg_rgig", (DL_FUNC) &_spTReg_rgig, 4},
    {"_spTReg_rig", (DL_FUNC) &_spTReg_rig, 5},
    {"_spTReg_ralRcpp", (DL_FUNC) &_spTReg_ralRcpp, 2},
    {"_spTReg_RandomMultiNormalC", (DL_FUNC) &_spTReg_RandomMultiNormalC, 2},
    {"_spTReg_ffbs", (DL_FUNC) &_spTReg_ffbs, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_spTReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
