# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dtnorm <- function(x, mu, sigma, a, b) {
    .Call('_spTReg_dtnorm', PACKAGE = 'spTReg', x, mu, sigma, a, b)
}

rtnorm <- function(mu, sigma, a, b) {
    .Call('_spTReg_rtnorm', PACKAGE = 'spTReg', mu, sigma, a, b)
}

psi1 <- function(x, alpha, lambda) {
    .Call('_spTReg_psi1', PACKAGE = 'spTReg', x, alpha, lambda)
}

psi2 <- function(x, alpha, lambda) {
    .Call('_spTReg_psi2', PACKAGE = 'spTReg', x, alpha, lambda)
}

rgig <- function(N, a, b, nu) {
    .Call('_spTReg_rgig', PACKAGE = 'spTReg', N, a, b, nu)
}

rig <- function(N, mu, lambda) {
    .Call('_spTReg_rig', PACKAGE = 'spTReg', N, mu, lambda)
}

ral <- function(N, theta, w2Inv, sigma) {
    .Call('_spTReg_ral', PACKAGE = 'spTReg', N, theta, w2Inv, sigma)
}

iidMeanRcpp <- function(Y, X, M, P, ga, gb, beta, prec, N, k, keep, nSims, nThin, nBurnin, nReport) {
    .Call('_spTReg_iidMeanRcpp', PACKAGE = 'spTReg', Y, X, M, P, ga, gb, beta, prec, N, k, keep, nSims, nThin, nBurnin, nReport)
}

iidQuantileRcpp <- function(tau, Y, X, M, P, ga, gb, beta, prec, N, k, keep, nSims, nThin, nBurnin, nReport) {
    .Call('_spTReg_iidQuantileRcpp', PACKAGE = 'spTReg', tau, Y, X, M, P, ga, gb, beta, prec, N, k, keep, nSims, nThin, nBurnin, nReport)
}

arMeanRcpp <- function(Y, X, N, k, beta, rho, prec, keep, nSims, nThin, nBurnin, nReport) {
    .Call('_spTReg_arMeanRcpp', PACKAGE = 'spTReg', Y, X, N, k, beta, rho, prec, keep, nSims, nThin, nBurnin, nReport)
}

spTMeanRcpp <- function() {
    .Call('_spTReg_spTMeanRcpp', PACKAGE = 'spTReg')
}

spTQuantileRcpp <- function() {
    .Call('_spTReg_spTQuantileRcpp', PACKAGE = 'spTReg')
}

