# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iidMeanRcpp <- function(Y, X, M, P, ga, gb, beta, prec, N, p, nSims, nThin, nBurnin, nReport) {
    .Call('_spTReg_iidMeanRcpp', PACKAGE = 'spTReg', Y, X, M, P, ga, gb, beta, prec, N, p, nSims, nThin, nBurnin, nReport)
}

iidQuantileRcpp <- function(tau, Y, X, M, P, ga, gb, beta, prec, N, p, nSims, nThin, nBurnin, nReport, parallel, nThreads) {
    .Call('_spTReg_iidQuantileRcpp', PACKAGE = 'spTReg', tau, Y, X, M, P, ga, gb, beta, prec, N, p, nSims, nThin, nBurnin, nReport, parallel, nThreads)
}

spMeanRcpp <- function(Y, X, U, V, X_gamma, X_alpha, dist, M, P, prior_sigma, M_beta_gamma, P_beta_gamma, prior_rho_gamma, prior_sigma_gamma, M_beta_alpha, P_beta_alpha, prior_sigma_alpha, prior_phi_alpha, prior_rho_w, prior_sigma_w, prior_phi_w, beta, prec, gamma, beta_gamma, hp_gamma, alpha, beta_alpha, hp_alpha, Wtls, hp_w, N, n, T, L, p, q, r, p_gamma, p_alpha, wBool, site, year, yday, nSims, nThin, nBurnin, nReport) {
    .Call('_spTReg_spMeanRcpp', PACKAGE = 'spTReg', Y, X, U, V, X_gamma, X_alpha, dist, M, P, prior_sigma, M_beta_gamma, P_beta_gamma, prior_rho_gamma, prior_sigma_gamma, M_beta_alpha, P_beta_alpha, prior_sigma_alpha, prior_phi_alpha, prior_rho_w, prior_sigma_w, prior_phi_w, beta, prec, gamma, beta_gamma, hp_gamma, alpha, beta_alpha, hp_alpha, Wtls, hp_w, N, n, T, L, p, q, r, p_gamma, p_alpha, wBool, site, year, yday, nSims, nThin, nBurnin, nReport)
}

spQuantileRcpp <- function(tau, Y, X, U, V, X_gamma, X_alpha, dist, M, P, prior_sigma, M_beta_gamma, P_beta_gamma, prior_rho_gamma, prior_sigma_gamma, M_beta_alpha, P_beta_alpha, prior_sigma_alpha, prior_phi_alpha, prior_rho_w, prior_sigma_w, prior_phi_w, beta, prec, gamma, beta_gamma, hp_gamma, alpha, beta_alpha, hp_alpha, Wtls, hp_w, N, n, T, L, p, q, r, p_gamma, p_alpha, wBool, site, year, yday, nSims, nThin, nBurnin, nReport, parallel, nThreads) {
    .Call('_spTReg_spQuantileRcpp', PACKAGE = 'spTReg', tau, Y, X, U, V, X_gamma, X_alpha, dist, M, P, prior_sigma, M_beta_gamma, P_beta_gamma, prior_rho_gamma, prior_sigma_gamma, M_beta_alpha, P_beta_alpha, prior_sigma_alpha, prior_phi_alpha, prior_rho_w, prior_sigma_w, prior_phi_w, beta, prec, gamma, beta_gamma, hp_gamma, alpha, beta_alpha, hp_alpha, Wtls, hp_w, N, n, T, L, p, q, r, p_gamma, p_alpha, wBool, site, year, yday, nSims, nThin, nBurnin, nReport, parallel, nThreads)
}

spTMeanRcpp <- function() {
    .Call('_spTReg_spTMeanRcpp', PACKAGE = 'spTReg')
}

spTQuantileRcpp <- function() {
    .Call('_spTReg_spTQuantileRcpp', PACKAGE = 'spTReg')
}

krigeBayesRcpp <- function(w, hp, coords, newcoords, parallel = FALSE, nThreads = 0L) {
    .Call('_spTReg_krigeBayesRcpp', PACKAGE = 'spTReg', w, hp, coords, newcoords, parallel, nThreads)
}

dist1 <- function(coords) {
    .Call('_spTReg_dist1', PACKAGE = 'spTReg', coords)
}

dist2 <- function(coords) {
    .Call('_spTReg_dist2', PACKAGE = 'spTReg', coords)
}

dist_mat <- function(A, B) {
    .Call('_spTReg_dist_mat', PACKAGE = 'spTReg', A, B)
}

dtnorm <- function(x, mu, sigma, a, b) {
    .Call('_spTReg_dtnorm', PACKAGE = 'spTReg', x, mu, sigma, a, b)
}

rtnorm <- function(mu, sigma, a, b) {
    .Call('_spTReg_rtnorm', PACKAGE = 'spTReg', mu, sigma, a, b)
}

psi1 <- function(x, alpha, lambda) {
    .Call('_spTReg_psi1', PACKAGE = 'spTReg', x, alpha, lambda)
}

psi2 <- function(x, alpha, lambda) {
    .Call('_spTReg_psi2', PACKAGE = 'spTReg', x, alpha, lambda)
}

rgig <- function(N, a, b, nu) {
    .Call('_spTReg_rgig', PACKAGE = 'spTReg', N, a, b, nu)
}

rig <- function(N, mu, lambda, parallel, nThreads) {
    .Call('_spTReg_rig', PACKAGE = 'spTReg', N, mu, lambda, parallel, nThreads)
}

ralRcpp <- function(sigma, tau) {
    .Call('_spTReg_ralRcpp', PACKAGE = 'spTReg', sigma, tau)
}

RandomMultiNormalC <- function(Q, b) {
    .Call('_spTReg_RandomMultiNormalC', PACKAGE = 'spTReg', Q, b)
}

ffbs <- function(Y, rho, Sigma_w, D_list) {
    .Call('_spTReg_ffbs', PACKAGE = 'spTReg', Y, rho, Sigma_w, D_list)
}

